apiVersion: v1
kind: Pod
metadata:
  name: pod-udacity-frontend
spec:
  containers:
  - image: virenderm01/udacity-frontend:local
    name: udacity-frontend
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1024Mi"
        cpu: "500m"       
    ports:
    - containerPort: 8080
  restartPolicy: Always